apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

resources:
  - openstack-crossplane-provider.yaml
  - deploymentRuntimeConfig.yaml
  - project.yaml
  - user.yaml
  - role.yaml
  - role_assignment.yaml
  - sg.yaml
  - quota.yaml
