apiVersion: v1
kind: ConfigMap
metadata:
  name: demo-nginx-html
  namespace: demo
data:
  index.html: |
    <!doctype html>
    <html>
      <head><meta charset="utf-8"><title>Hello</title></head>
      <body style="font-family: sans-serif;">
        <h1>Hello world</h1>
        <h2> hihieheh <h2>
      </body>
    </html>
